import Head from 'next/head'
import Board from './components/Board'

export default function Home() {
  return (
    <div className='container wrapper relative flex justify-around items-center'>
      <Head>
        <title>MERN Todo App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Board />
    </div>
  )
}
